// LOCALHOST
### Get all movies
GET http://localhost:3000/movies

### Get movie by id GET
http://localhost:3000/movies/65296ceaa05d58bdd4905425

### Create movie POST
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "title": "Lord of testing 2023",
    "genre": ["Crime", "Drama"],
    "releaseYear": {"$numberInt": "1972"},
    "director": "Francis Ford Coppola",
    "mainCast": ["Marlon Brando", "Al Pacino"],
    "rating": {"$numberDouble": "9.2"}
}

### PUT movie
PUT http://localhost:3001/movies/65296ceaa05d58bdd4905425  HTTP/1.1
content-type: application/json

{
    "title": "The Godfather 2023",
    "genre": ["Crime", "Drama"],
    "releaseYear": {"$numberInt": "1972"},
    "director": "Francis Ford Coppola",
    "mainCast": ["Marlon Brando", "Al Pacino"],
    "rating": {"$numberDouble": "9.2"}
}

### DELETE console
DELETE http://localhost:3000/movies/
